(function(){'use strict';
var state={home:null,route:'popular',settings:{stream_mode:'auto',app_icon:'kinopub'},current:null,authPoll:null,authTick:null,streamUrl:'',mode:'direct',episodeId:'',catalogCache:{},catalogRequest:0,cacheVersion:Date.now(),catalogPages:{},catalogTotals:{},searchTimer:null,searchSeq:0,suggestionIndex:-1,searchMode:'all',lastSearch:'',currentSuggestions:[],selectedSuggestion:null,profile:null,profileCheckedAt:0,profileTimer:null,authenticated:false,appInitialized:false,authRequired:false,watchedMap:{},progressMap:{},playerResumePosition:0,playerSwitching:false,playerStreams:[],playerSubtitles:[],playerAudios:[],playerQualityIndex:'',playerSubtitleChoice:'off',playerAudioChoice:'auto',audioApplyTimer:null,subtitleApplyTimer:null,playerOriginalDuration:0,hls:null,hlsUsing:false,hlsManifestReady:false,audioHlsActive:false,audioHlsOffset:0,audioHlsJobId:'',audioHlsPendingJobId:'',audioHlsPollToken:0,audioHlsPreparing:false,audioHlsSelectedIndex:-1,baseStreamUrl:'',baseStreamMode:'direct'};
var $=function(id){return document.getElementById(id);},video=$('video');

var dogBrandIcons=['assets/dog-icon-1.png','assets/dog-icon-2.png','assets/dog-icon-3.png'];
var dogBrandIndex=-1,brandingRotationTimer=null;
function normalizeAppIcon(value){return value==='kinopub'?'kinopub':'kinoterk';}
function selectedAppIcon(){var nodes=document.querySelectorAll('input[name="appIcon"]');for(var i=0;i<nodes.length;i++)if(nodes[i].checked)return normalizeAppIcon(nodes[i].value);return 'kinopub';}
function setFavicon(src,type){var link=$('appFavicon');if(!link){link=document.createElement('link');link.id='appFavicon';link.rel='icon';document.head.appendChild(link);}link.type=type||(/\.svg(?:$|\?)/i.test(src)?'image/svg+xml':'image/png');link.href=src;}
function nextDogBrandIcon(){var next;if(dogBrandIcons.length<2)next=0;else{do{next=Math.floor(Math.random()*dogBrandIcons.length);}while(next===dogBrandIndex);}dogBrandIndex=next;var src=dogBrandIcons[next],logo=$('brandLogo');if(logo)logo.src=src;setFavicon(src,'image/png');}
function stopBrandingRotation(){if(brandingRotationTimer){clearInterval(brandingRotationTimer);brandingRotationTimer=null;}}
function applyBranding(iconKey){var key=normalizeAppIcon(iconKey),logo=$('brandLogo'),text=$('brandText');stopBrandingRotation();if(key==='kinopub'){if(logo){logo.src='assets/kp-logo.svg';logo.classList.remove('dog-brand-logo');}if(text)text.textContent='kinopub';document.title='kinopub';setFavicon('assets/kp-logo.svg','image/svg+xml');document.body.setAttribute('data-app-brand','kinopub');return;}if(logo)logo.classList.add('dog-brand-logo');if(text)text.textContent='киноТёрк';document.title='киноТёрк';document.body.setAttribute('data-app-brand','kinoterk');nextDogBrandIcon();brandingRotationTimer=setInterval(nextDogBrandIcon,5*60*1000);}
function appBrandName(){return normalizeAppIcon(state.settings&&state.settings.app_icon)==='kinoterk'?'киноТёрк':'KinoPub';}

var routes={
 popular:{title:'Новинки',mode:'tabs',section:'movie',feed:'popular'},
 new:{title:'Новинки',mode:'tabs',section:'movie',feed:'fresh'},
 hot:{title:'Новинки',mode:'tabs',section:'movie',feed:'hot'},
 movie:{title:'Фильмы',mode:'category',section:'movie',feed:'all',show3d:true},
 serial:{title:'Сериалы',mode:'category',section:'serial',feed:'all'},
 anime:{title:'Аниме',mode:'category',section:'anime',feed:'all'},
 concert:{title:'Концерты',mode:'category',section:'concert',feed:'all'},
 documovie:{title:'Документальные фильмы',mode:'category',section:'documovie',feed:'all'},
 docuserial:{title:'Документальные сериалы',mode:'category',section:'docuserial',feed:'all'},
 tvshow:{title:'ТВ Шоу',mode:'category',section:'tvshow',feed:'all'},
 sport:{title:'Спорт',mode:'category',section:'sport',feed:'all'},
 settings:{title:'Настройки',mode:'settings'}
};
function esc(v){var d=document.createElement('div');d.textContent=String(v==null?'':v);return d.innerHTML;}
function fmt(s){s=isFinite(s)?Math.max(0,Math.floor(s)):0;var h=Math.floor(s/3600),m=Math.floor(s/60)%60,x=s%60;return(h?(h<10?'0':'')+h+':':'')+(m<10?'0':'')+m+':'+(x<10?'0':'')+x;}
function visibleFocus(){var n=document.querySelectorAll('.focusable:not([disabled])'),a=[];for(var i=0;i<n.length;i++)if(n[i].offsetParent!==null)a.push(n[i]);return a;}
function focusFirst(){var a=visibleFocus();if(a[0])a[0].focus();}
function bgCss(v,kind){if(!v)return '#283248';if(/^https?:/i.test(v)){var clean=String(v).replace(/"/g,'');var isBackdrop=kind==='backdrop';var w=isBackdrop?1280:420,h=isBackdrop?720:630,q=isBackdrop?80:82;return 'center/cover no-repeat url("'+KPApi.imageProxyUrl(clean,state.cacheVersion,w,h,q)+'")';}return v;}
function ratingText(value){var n=parseFloat(value);if(!isFinite(n)||n<0||n>10)return '—';return n.toFixed(1).replace('.0','');}
function kinopubText(item){return ratingText(item.rating);}
function ratings(item){return [kinopubText(item),ratingText(item.imdb_rating),ratingText(item.kinopoisk_rating)];}
function watchedStatus(item){var id=String(item&&item.id||'');if(item&&item.watched===1)return 1;if(item&&item.watched===0)return 0;if(state.watchedMap[id]!==undefined)return state.watchedMap[id];return -1;}
function card(item){var p=ratings(item),status=watchedStatus(item),b=document.createElement('button');b.className='media-card focusable';var mark=status===1?'<div class="watched-overlay"><span>ПРОСМОТРЕНО</span></div>':(status===0?'<div class="continue-overlay"><span>ПРОДОЛЖИТЬ</span></div>':'');b.innerHTML='<div class="poster-art">'+mark+'<div class="poster-badges"><span title="Субтитры"><svg><use xlink:href="#i-subtitles"></use></svg></span><span title="Dolby"><svg><use xlink:href="#i-dolby"></use></svg></span><span title="HD"><svg><use xlink:href="#i-hd"></use></svg></span></div><div class="poster-ratings"><span><svg><use xlink:href="#i-thumb"></use></svg>'+p[0]+'</span><span><svg><use xlink:href="#i-imdb"></use></svg>'+p[1]+'</span><span><svg><use xlink:href="#i-kp"></use></svg>'+p[2]+'</span></div></div><div class="item-title">'+esc(item.title||'')+'</div><div class="item-author">'+esc(item.original_title||'')+'</div>';var poster=b.querySelector('.poster-art');if(poster)poster.style.background=bgCss(item.poster,'poster');b.onclick=function(){state.current=item;openDetails(item);};b.onfocus=function(){state.current=item;};return b;}
function renderTop(){var cfg=routes[state.route]||routes.popular,root=$('catalogTop');root.innerHTML='';if(cfg.mode==='tabs'){var row=document.createElement('div');row.className='tab-row';var tabs=[['popular','Популярные'],['new','Свежие'],['hot','Горячие']];for(var i=0;i<tabs.length;i++){var bt=document.createElement('button');bt.className='focusable catalog-tab'+(state.route===tabs[i][0]?' active':'');bt.textContent=tabs[i][1];bt.onclick=(function(r){return function(){route(r);};}(tabs[i][0]));row.appendChild(bt);}root.appendChild(row);return;}var head=document.createElement('div');head.className='catalog-title-row';var title='<h3>';if(cfg.show3d)title+='<span class="title-main">Фильмы</span><span class="title-sep">&nbsp;</span><button class="focusable title-link" data-route-inline="3d">3D</button>';else title+=esc(cfg.title);title+='</h3><button id="filterToggle" class="focusable filter-toggle">Фильтры ▾</button>';head.innerHTML=title;root.appendChild(head);var f=head.querySelector('[data-route-inline="3d"]');if(f)f.onclick=function(){route('movie');};var t=head.querySelector('#filterToggle');if(t)t.onclick=toggleFilters;}
function toggleFilters(){var old=$('filterPanel');if(old){old.parentNode.removeChild(old);return;}var panel=document.createElement('div');panel.id='filterPanel';panel.className='filter-panel';var labels=['Жанр','Страна','Год','Качество','Субтитры','Сортировка'];for(var i=0;i<labels.length;i++)panel.innerHTML+='<label>'+labels[i]+'<select class="focusable"><option>Любые</option></select></label>';$('catalogTop').appendChild(panel);setTimeout(focusFirst,10);}
function catalogPageKey(cfg){return cfg.section+':'+cfg.feed;}
function currentCatalogPage(cfg){var key=catalogPageKey(cfg);return state.catalogPages[key]||0;}
function setCatalogPage(page){var cfg=routes[state.route]||routes.popular,key=catalogPageKey(cfg);state.catalogPages[key]=Math.max(0,page||0);renderCatalog();setTimeout(function(){try{$('catalogTop').scrollIntoView(true);}catch(e){}},20);}
function pageButton(label,page,active,disabled,extraClass){var b=document.createElement('button');b.className='focusable page-button'+(active?' active':'')+(extraClass?' '+extraClass:'');b.textContent=label;b.disabled=!!disabled;if(!disabled)b.onclick=function(){setCatalogPage(page);};return b;}
function renderPagination(meta,itemCount){
 var root=$('catalogPagination');root.innerHTML='';
 var current=Math.max(0,parseInt(meta&&meta.page,10)||0),totalPages=Math.max(0,parseInt(meta&&meta.total_pages,10)||0),knownTotal=totalPages>0,hasItems=itemCount>0,pageFull=itemCount>=48;
 if(!hasItems&&current===0){root.classList.add('hidden');return;}
 root.classList.remove('hidden');
 // KinoPub keeps ten numeric buttons around the current page. Near the end,
 // show the final ten pages instead of only the last two or three.
 var start=knownTotal?Math.max(0,Math.min(current-5,Math.max(0,totalPages-10))):Math.max(0,current-5);
 var end=knownTotal?Math.min(totalPages,start+10):start+10;
 var definitelyLast=!pageFull && hasItems;
 if(current>0){
   root.appendChild(pageButton('<<',0,false,false,'first'));
   root.appendChild(pageButton('<',Math.max(0,current-1),false,false,'prev'));
 }
 for(var i=start;i<end;i++)root.appendChild(pageButton(String(i+1),i,i===current,false,''));
 var canNext=!definitelyLast && (!knownTotal || current+1<totalPages || pageFull);
 var lastTarget=knownTotal?Math.max(0,totalPages-1):end;
 var canLast=knownTotal?current<totalPages-1:pageFull;
 if(canNext)root.appendChild(pageButton('>',current+1,false,false,'next'));
 if(canLast)root.appendChild(pageButton('>>',lastTarget,false,false,'last'));
}
function discoverTotalPages(cfg,meta,itemCount,forceRefresh){
 var key=catalogPageKey(cfg),known=state.catalogTotals[key];
 if(known>1&&!forceRefresh){meta.total_pages=Math.max(known,meta.total_pages||0);renderPagination(meta,itemCount);return;}
 KPApi.pageCount(cfg.section,cfg.feed,!!forceRefresh).then(function(info){
   var total=parseInt(info&&info.total_pages,10)||0;if(!total)return;
   // Treat probed totals as a lower bound. Shortcut feeds can expose more pages
   // than an earlier probe found, so never shrink a total already reached.
   total=Math.max(total,(parseInt(meta.page,10)||0)+1,state.catalogTotals[key]||0);
   state.catalogTotals[key]=total;meta.total_pages=total;
   for(var cacheKey in state.catalogCache){if(cacheKey.indexOf(key+':')===0)state.catalogCache[cacheKey].meta.total_pages=Math.max(state.catalogCache[cacheKey].meta.total_pages||0,total);}
   renderPagination(meta,itemCount);
 }).catch(function(err){KPApi.report('Page count discovery failed',{section:cfg.section,feed:cfg.feed,error:String(err)},'catalog').catch(function(){});});
}
function renderCatalog(){
 renderTop();
 var cfg=routes[state.route]||routes.popular,g=$('catalogGrid'),page=currentCatalogPage(cfg),cacheKey=catalogPageKey(cfg)+':'+page;
 g.innerHTML='<p class="empty-state">Загрузка раздела…</p>';$('catalogPagination').classList.add('hidden');
 var cached=state.catalogCache[cacheKey];
 if(cached){renderCatalogItems(cached.items);renderPagination(cached.meta,cached.items.length);if(page===0||!cached.meta.total_pages||cached.meta.total_pages<=1)discoverTotalPages(cfg,cached.meta,cached.items.length);return;}
 var requestId=++state.catalogRequest;
 KPApi.catalog(cfg.section,cfg.feed,page,state.cacheVersion).then(function(data){
   if(requestId!==state.catalogRequest)return;
   var items=(data&&data.items)||[],meta={page:data&&data.page||0,total_pages:data&&data.total_pages||0,total_items:data&&data.total_items||0,has_next:!!(data&&data.has_next)};
   var totalKey=catalogPageKey(cfg),reached=(parseInt(meta.page,10)||0)+1;
   if(reached>1&&reached>(state.catalogTotals[totalKey]||0))state.catalogTotals[totalKey]=reached;
   meta.total_pages=Math.max(meta.total_pages||0,state.catalogTotals[totalKey]||0);
   state.catalogCache[cacheKey]={items:items,meta:meta};
   renderCatalogItems(items);renderPagination(meta,items.length);
   if(page===0||!meta.total_pages||meta.total_pages<=1)discoverTotalPages(cfg,meta,items.length,false);
   else if(items.length>=48&&meta.total_pages&&reached>=meta.total_pages)discoverTotalPages(cfg,meta,items.length,true);
 }).catch(function(err){
   if(requestId!==state.catalogRequest)return;
   g.innerHTML='<p class="empty-state">Не удалось загрузить раздел: '+esc(err&&err.message?err.message:String(err))+'</p>';$('catalogPagination').classList.add('hidden');
   KPApi.report('Catalogue section failed',{route:state.route,section:cfg.section,feed:cfg.feed,page:page,error:String(err)},'catalog').catch(function(){});
 });
}
function renderCatalogItems(items){var g=$('catalogGrid');g.innerHTML='';for(var i=0;i<items.length;i++)g.appendChild(card(items[i]));if(!items.length)g.innerHTML='<p class="empty-state">В этом разделе '+esc(appBrandName())+' пока не вернул контент</p>';}

function resetNavigationState(name){var cfg=routes[name];if(cfg){state.catalogPages[catalogPageKey(cfg)]=0;}var input=$('searchInput');if(input)input.value='';state.lastSearch='';state.selectedSuggestion=null;state.currentSuggestions=[];state.suggestionIndex=-1;if(state.searchTimer){clearTimeout(state.searchTimer);state.searchTimer=null;}state.searchSeq++;hideSuggestions();}
function route(name){if(name==='settings'){state.route=name;$('catalogScreen').classList.add('hidden');$('searchScreen').classList.add('hidden');$('settingsScreen').classList.remove('hidden');loadSettings();}else{resetNavigationState(name);state.route=name;$('catalogScreen').classList.remove('hidden');$('searchScreen').classList.add('hidden');$('settingsScreen').classList.add('hidden');renderCatalog();}var links=document.querySelectorAll('[data-route]');for(var i=0;i<links.length;i++)links[i].classList.toggle('active',links[i].getAttribute('data-route')===name || (name==='new'&&links[i].getAttribute('data-route')==='popular'));setTimeout(focusFirst,20);}
function renderDetails(item){state.current=item;$('detailsTitle').textContent=item.title;$('detailsMeta').textContent=[item.original_title||'',item.year,item.rating?('★ '+item.rating):'',(item.genres||[]).join(' · ')].filter(Boolean).join('   ');$('detailsDescription').textContent=item.description||'';$('detailsBackdrop').style.background=bgCss(item.backdrop||item.poster,'backdrop');var ep=$('episodes');ep.innerHTML='';if(item.seasons&&item.seasons.length){for(var s=0;s<item.seasons.length;s++){var h=document.createElement('h3');h.textContent='Сезон '+item.seasons[s].number;ep.appendChild(h);var row=document.createElement('div');row.className='episode-row';var episodes=item.seasons[s].episodes||[];for(var e=0;e<episodes.length;e++){var x=episodes[e],bt=document.createElement('button');bt.className='focusable episode';bt.textContent=(x.episode||x.number||e+1)+'. '+(x.title||'Серия');bt.onclick=(function(epi){return function(){play(item,epi);};}(x));row.appendChild(bt);}ep.appendChild(row);}}else if(item.media&&item.media.length>1){var mediaRow=document.createElement('div');mediaRow.className='episode-row';for(var m=0;m<item.media.length;m++){var media=item.media[m],mb=document.createElement('button');mb.className='focusable episode';mb.textContent=media.title||('Видео '+(m+1));mb.onclick=(function(entry){return function(){play(item,entry);};}(media));mediaRow.appendChild(mb);}ep.appendChild(mediaRow);}$('detailsModal').classList.remove('hidden');setTimeout(function(){$('detailsPlay').focus();},20);}
function openDetails(item){state.current=item;$('detailsModal').classList.remove('hidden');$('detailsTitle').textContent='Загрузка…';$('detailsDescription').textContent='Получаем сведения и список видео';$('episodes').innerHTML='';KPApi.item(item.id).then(function(full){for(var k in item)if(full[k]===undefined)full[k]=item[k];renderDetails(full);}).catch(function(){renderDetails(item);});}
function closeDetails(){$('detailsModal').classList.add('hidden');}
function bestStream(item){var list=item.streams||[];return list.length?list[0]:null;}
function optionText(value,fallback){if(value===null||value===undefined)return fallback||'';if(typeof value==='string'||typeof value==='number')return String(value);return String(value.title||value.name||value.label||value.language||value.lang||value.locale||value.quality||fallback||'');}
function optionUrl(value){if(!value)return '';if(typeof value==='string')return value.indexOf('http')===0?value:'';return value.url||value.src||value.file||value.link||'';}
function streamQualityLabel(st,index){var q=st.quality||((st.height||'')+(st.height?'p':''));if(!q)q='Вариант '+(index+1);var extra=[];if(st.codec)extra.push(String(st.codec).toUpperCase());if(st.source_type)extra.push(String(st.source_type).toUpperCase());return String(q)+(extra.length?' · '+extra.join(' · '):'');}
function streamGroupKey(st){if(st&&st.file)return 'file:'+String(st.file);return [st&&st.height||'',st&&st.width||'',st&&st.quality||'',st&&st.codec||''].join('|');}
function preparePlayerOptions(result,selected){var streams=result.streams||[],groups=[],byKey={};for(var i=0;i<streams.length;i++){var st=streams[i];if(!st||!st.url)continue;var key=streamGroupKey(st),group=byKey[key];if(!group){group={quality:st.quality,height:st.height,width:st.width,codec:st.codec,file:st.file,variants:{},url:st.url,source_type:st.source_type,protocol:st.protocol};byKey[key]=group;groups.push(group);}var type=String(st.source_type||st.protocol||'http').toLowerCase();group.variants[type]=st.url;if(type.indexOf('hls')===0&&!group.variants.hls)group.variants.hls=st.url;if((type==='http'||st.protocol==='http')&&!group.variants.http)group.variants.http=st.url;}
groups.sort(function(a,b){return Number(b.height||0)-Number(a.height||0);});for(var g=0;g<groups.length;g++){groups[g].source_type=groups[g].variants.hls?'hls':'http';groups[g].protocol=groups[g].variants.hls?'hls':'http';groups[g].url=groups[g].variants.http||groups[g].variants.hls||groups[g].url;}
state.playerStreams=groups;state.playerSubtitles=result.subtitles||((result.media&&result.media.subtitles)||[]);state.playerAudios=filterApiAudios(result.audios||((result.media&&result.media.audios)||[]),result.media||{});var q=$('playerQuality');q.innerHTML='';for(var j=0;j<groups.length;j++){var o=document.createElement('option');o.value=String(j);o.textContent=streamQualityLabel(groups[j],j);q.appendChild(o);}var selectedIndex=0;for(var k=0;k<groups.length;k++){var variants=groups[k].variants||{};if(selected&&((selected.file&&groups[k].file===selected.file)||variants.http===selected.url||variants.hls===selected.url||variants.hls2===selected.url||variants.hls4===selected.url)){selectedIndex=k;break;}}state.playerQualityIndex=String(selectedIndex);q.value=state.playerQualityIndex;populateSubtitleMenu();populateAudioMenu();}
function currentQualityGroup(){return state.playerStreams[Number(state.playerQualityIndex)||0]||state.playerStreams[0]||null;}
function streamUrlForGroup(group,mode){if(!group)return '';var variants=group.variants||{};if(mode==='hls')return variants.hls4||variants.hls2||variants.hls||variants.http||group.url||'';return variants.http||variants.hls||variants.hls2||variants.hls4||group.url||'';}
function currentHttpAudioSource(){var group=currentQualityGroup(),variants=group&&group.variants||{};return variants.http||'';}
function subtitleFormat(value){var raw=audioScalar(value).toLowerCase();if(!raw)return '';if(raw.indexOf('webvtt')>=0||raw==='vtt')return 'WebVTT';if(raw.indexOf('subrip')>=0||raw==='srt')return 'SRT';if(raw.indexOf('ass')>=0||raw.indexOf('ssa')>=0)return 'ASS/SSA';if(raw.indexOf('pgs')>=0||raw.indexOf('sup')>=0)return 'PGS';return audioScalar(value).toUpperCase();}
function detailedSubtitleLabel(track,index,isNative){var parts=[],language='',title='',translation='',kind='',format='',forced='',hearing='';if(isNative){language=track.language||track.srclang||'';title=track.label||'';kind=track.kind||'';}else if(track&&typeof track==='object'){language=firstAudioValue(track,['language_name','language','lang','locale','iso_639_1','iso_639_2']);title=firstAudioValue(track,['title','name','label','display_name']);translation=firstAudioValue(track,['translation','translator','studio','team','author']);kind=firstAudioValue(track,['kind','type','subtitle_type','category']);format=firstAudioValue(track,['format','codec','extension','format_name']);forced=firstAudioValue(track,['forced','is_forced']);hearing=firstAudioValue(track,['hearing_impaired','sdh','is_sdh']);}else{title=String(track||'');}var langName=audioLanguageName(language);if(langName)parts.push(langName);function pushUnique(value){value=audioScalar(value);if(!value||value==='[object Object]')return;var low=value.toLowerCase();for(var k=0;k<parts.length;k++)if(String(parts[k]).toLowerCase()===low)return;parts.push(value);}pushUnique(title);pushUnique(translation);var kindLow=String(kind||'').toLowerCase();if(kindLow==='captions')pushUnique('для слабослышащих');else if(kindLow&&kindLow!=='subtitles')pushUnique(kind);var forcedLow=String(forced||'').toLowerCase();if(forced===true||forced===1||forcedLow==='true'||forcedLow==='1'||forcedLow==='yes')pushUnique('форсированные');var hearingLow=String(hearing||'').toLowerCase();if(hearing===true||hearing===1||hearingLow==='true'||hearingLow==='1'||hearingLow==='yes')pushUnique('SDH');pushUnique(subtitleFormat(format));if(!parts.length)parts.push('Субтитры '+(index+1));return (index+1)+'. '+parts.join(' · ');}
function subtitleHasUrl(track){return !!optionUrl(track);}
function populateSubtitleMenu(){var select=$('playerSubtitles'),nativeCount=video.textTracks&&video.textTracks.length?video.textTracks.length:0,apiCount=state.playerSubtitles&&state.playerSubtitles.length?state.playerSubtitles.length:0,count=Math.max(nativeCount,apiCount);select.innerHTML='<option value="off">Выкл.</option>';for(var i=0;i<count;i++){var apiTrack=apiCount>i?state.playerSubtitles[i]:null,nativeTrack=nativeCount>i?video.textTracks[i]:null,o=document.createElement('option');o.value='track:'+i;o.textContent=apiTrack?detailedSubtitleLabel(apiTrack,i,false):detailedSubtitleLabel(nativeTrack||{},i,true);o.disabled=!nativeTrack&&!subtitleHasUrl(apiTrack);select.appendChild(o);}select.disabled=count===0;select.value=state.playerSubtitleChoice;if(select.selectedIndex<0){state.playerSubtitleChoice='off';select.value='off';}}
function clearExternalTracks(){var tracks=video.querySelectorAll('track[data-kp-external]');for(var i=0;i<tracks.length;i++)tracks[i].remove();}
function disableAllTextTracks(){if(!video.textTracks)return;for(var i=0;i<video.textTracks.length;i++){try{video.textTracks[i].mode='disabled';}catch(e){}}}
function enableNativeSubtitle(index){if(!video.textTracks||!video.textTracks[index])return false;disableAllTextTracks();try{video.textTracks[index].mode='showing';return video.textTracks[index].mode==='showing';}catch(e){return false;}}
function applySubtitleChoice(choice){state.playerSubtitleChoice=choice||'off';if(state.subtitleApplyTimer){clearTimeout(state.subtitleApplyTimer);state.subtitleApplyTimer=null;}disableAllTextTracks();clearExternalTracks();if(state.playerSubtitleChoice==='off')return;var index=Number(String(state.playerSubtitleChoice).split(':')[1]);if(!isFinite(index))return;var apiTrack=state.playerSubtitles[index]||null,url=optionUrl(apiTrack);if(url){var track=document.createElement('track');track.setAttribute('data-kp-external','1');track.kind='subtitles';track.label=detailedSubtitleLabel(apiTrack,index,false);track.srclang=audioScalar(apiTrack&&typeof apiTrack==='object'&&(apiTrack.language||apiTrack.lang||apiTrack.locale))||'ru';track.src=KPApi.subtitleProxyUrl(url,state.audioHlsActive?state.audioHlsOffset:0);track.default=true;video.appendChild(track);var tries=0;function showExternal(){tries++;disableAllTextTracks();try{if(track.track)track.track.mode='showing';}catch(e){}if((!track.track||track.track.mode!=='showing')&&tries<8)state.subtitleApplyTimer=setTimeout(showExternal,250);}track.onload=showExternal;state.subtitleApplyTimer=setTimeout(showExternal,100);return;}var attempts=0;function showNative(){attempts++;var ok=enableNativeSubtitle(index);if(!ok&&attempts<8)state.subtitleApplyTimer=setTimeout(showNative,250);}showNative();}
function audioLanguageName(code){var raw=String(code||'').trim(),key=raw.toLowerCase().replace('_','-').split('-')[0];var names={ru:'Русский',rus:'Русский',uk:'Украинский',ukr:'Украинский',en:'Английский',eng:'Английский',de:'Немецкий',deu:'Немецкий',ger:'Немецкий',fr:'Французский',fra:'Французский',fre:'Французский',es:'Испанский',spa:'Испанский',it:'Итальянский',ita:'Итальянский',ja:'Японский',jpn:'Японский',ko:'Корейский',kor:'Корейский',zh:'Китайский',zho:'Китайский',chi:'Китайский',pl:'Польский',pol:'Польский',tr:'Турецкий',tur:'Турецкий'};return names[key]||raw;}
function audioScalar(value){if(value===undefined||value===null)return '';if(typeof value==='string'||typeof value==='number'||typeof value==='boolean'){var text=String(value).trim();return text==='[object Object]'?'':text;}if(Array.isArray(value)){for(var i=0;i<value.length;i++){var arrayText=audioScalar(value[i]);if(arrayText)return arrayText;}return '';}if(typeof value==='object'){var preferred=['title','name','label','display_name','short_name','studio','team','author','type','voice','translation','language_name','language','lang','codec','format_name','value'];for(var j=0;j<preferred.length;j++){if(Object.prototype.hasOwnProperty.call(value,preferred[j])){var nested=audioScalar(value[preferred[j]]);if(nested)return nested;}}return '';}return '';}
function firstAudioValue(obj,keys){if(!obj||typeof obj!=='object')return '';for(var i=0;i<keys.length;i++){var v=audioScalar(obj[keys[i]]);if(v)return v;}return '';}
function normalizeChannels(value){var v=String(value||'').trim();if(!v)return '';var low=v.toLowerCase();if(low==='2'||low==='2.0'||low==='stereo')return '2.0';if(low==='1'||low==='1.0'||low==='mono')return '1.0';if(low==='6'||low==='5.1')return '5.1';if(low==='8'||low==='7.1')return '7.1';return v;}
function detailedAudioLabel(track,index,isNative){var parts=[],language='',title='',translation='',voice='',channels='',codec='',bitrate='';if(isNative){language=track.language||track.srclang||'';title=track.label||'';codec=track.codec||'';channels=track.channels||'';}else if(track&&typeof track==='object'){language=firstAudioValue(track,['language_name','language','lang','locale','iso_639_1','iso_639_2']);title=firstAudioValue(track,['title','name','label','display_name']);translation=firstAudioValue(track,['translation','translator','studio','team','author','voice_studio']);voice=firstAudioValue(track,['voice','voice_type','translation_type','type','format']);channels=firstAudioValue(track,['channels','channel_layout','audio_channels']);codec=firstAudioValue(track,['codec','audio_codec','format_name']);bitrate=firstAudioValue(track,['bitrate','audio_bitrate']);}else{title=String(track||'');}
var langName=audioLanguageName(language);if(langName)parts.push(langName);function pushUnique(value){value=audioScalar(value);if(!value||value==='[object Object]')return;var low=value.toLowerCase();for(var k=0;k<parts.length;k++)if(String(parts[k]).toLowerCase()===low)return;parts.push(value);}pushUnique(title);pushUnique(translation);pushUnique(voice);pushUnique(normalizeChannels(channels));pushUnique(codec?String(codec).toUpperCase():'');if(bitrate){var b=Number(bitrate);pushUnique(isFinite(b)&&b>1000?Math.round(b/1000)+' kbps':bitrate);}if(!parts.length)parts.push('Дорожка '+(index+1));return (index+1)+'. '+parts.join(' · ');}
function isGenericTrackLabel(value){var text=audioScalar(value).toLowerCase();return !text||/^track\s*\d*$/.test(text)||/^audio\s*\d*$/.test(text)||/^дорожка\s*\d*$/.test(text);}
function mergedAudioLabel(nativeTrack,apiTrack,index){if(apiTrack){var apiLabel=detailedAudioLabel(apiTrack,index,false);if(apiLabel&&apiLabel.indexOf('Дорожка '+(index+1))<0)return apiLabel;}if(nativeTrack&&!isGenericTrackLabel(nativeTrack.label))return detailedAudioLabel(nativeTrack,index,true);if(apiTrack)return detailedAudioLabel(apiTrack,index,false);return detailedAudioLabel(nativeTrack||{},index,true);}
function audioApiIndex(apiTrack,fallback){if(apiTrack&&typeof apiTrack==='object'){var raw=apiTrack.index!=null?apiTrack.index:(apiTrack.track_index!=null?apiTrack.track_index:apiTrack.stream_index),n=Number(raw);if(isFinite(n)&&n>0)return n;}return fallback+1;}
function normalizeChannels(value){var v=String(value||'').trim();if(!v)return '';var low=v.toLowerCase();if(low==='2'||low==='2.0'||low==='stereo')return '2.0';if(low==='1'||low==='1.0'||low==='mono')return '1.0';if(low==='6'||low==='5.1')return '5.1';if(low==='8'||low==='7.1')return '7.1';return v;}
function detailedAudioLabel(track,index,isNative){var parts=[],language='',title='',translation='',voice='',channels='',codec='',bitrate='';if(isNative){language=track.language||track.srclang||'';title=track.label||'';codec=track.codec||'';channels=track.channels||'';}else if(track&&typeof track==='object'){language=firstAudioValue(track,['language_name','language','lang','locale','iso_639_1','iso_639_2']);title=firstAudioValue(track,['title','name','label','display_name']);translation=firstAudioValue(track,['translation','translator','studio','team','author','voice_studio']);voice=firstAudioValue(track,['voice','voice_type','translation_type','type','format']);channels=firstAudioValue(track,['channels','channel_layout','audio_channels']);codec=firstAudioValue(track,['codec','audio_codec','format_name']);bitrate=firstAudioValue(track,['bitrate','audio_bitrate']);}else{title=String(track||'');}var langName=audioLanguageName(language);if(langName)parts.push(langName);function pushUnique(value){value=audioScalar(value);if(!value||value==='[object Object]')return;var low=value.toLowerCase();for(var k=0;k<parts.length;k++)if(String(parts[k]).toLowerCase()===low)return;parts.push(value);}pushUnique(title);pushUnique(translation);pushUnique(voice);pushUnique(normalizeChannels(channels));pushUnique(codec?String(codec).toUpperCase():'');if(bitrate){var b=Number(bitrate);pushUnique(isFinite(b)&&b>1000?Math.round(b/1000)+' kbps':bitrate);}if(!parts.length)parts.push('Дорожка '+(index+1));return (index+1)+'. '+parts.join(' · ');}
function isGenericTrackLabel(value){var text=audioScalar(value).toLowerCase();return !text||/^track\s*\d*$/.test(text)||/^audio\s*\d*$/.test(text)||/^дорожка\s*\d*$/.test(text);}
function mergedAudioLabel(nativeTrack,apiTrack,index){if(apiTrack){var apiLabel=detailedAudioLabel(apiTrack,index,false);if(apiLabel&&apiLabel.indexOf('Дорожка '+(index+1))<0)return apiLabel;}if(nativeTrack&&!isGenericTrackLabel(nativeTrack.label))return detailedAudioLabel(nativeTrack,index,true);if(apiTrack)return detailedAudioLabel(apiTrack,index,false);return detailedAudioLabel(nativeTrack||{},index,true);}
function audioApiIndex(apiTrack,fallback){if(apiTrack&&typeof apiTrack==='object'){var raw=apiTrack.index!=null?apiTrack.index:(apiTrack.track_index!=null?apiTrack.track_index:apiTrack.stream_index),n=Number(raw);if(isFinite(n)&&n>0)return n;}return fallback+1;}
function parseMediaTrackIndexes(media){var raw=media&&media.tracks,set={},has=false;if(Array.isArray(raw)){for(var i=0;i<raw.length;i++){var n=Number(raw[i]);if(isFinite(n)&&n>0){set[n]=true;has=true;}}}else if(typeof raw==='string'||typeof raw==='number'){var parts=String(raw).split(/[^0-9]+/);for(var j=0;j<parts.length;j++){var m=Number(parts[j]);if(isFinite(m)&&m>0){set[m]=true;has=true;}}}return has?set:null;}
function filterApiAudios(list,media){/* KinoPub's media.tracks can describe only the active/default track in some real responses. The audios array is the authoritative list for the selector, so do not hide entries here. */return Array.isArray(list)?list:[];}
function populateAudioMenu(){var select=$('playerAudio');select.innerHTML='<option value="auto">Авто</option>';var nativeCount=video.audioTracks&&video.audioTracks.length?video.audioTracks.length:0,hlsCount=state.hls&&state.hls.audioTracks?state.hls.audioTracks.length:0,apiCount=state.playerAudios&&state.playerAudios.length?state.playerAudios.length:0,count=apiCount||Math.max(nativeCount,hlsCount);for(var i=0;i<count;i++){var nativeTrack=nativeCount>i?video.audioTracks[i]:null,apiTrack=apiCount>i?state.playerAudios[i]:null,o=document.createElement('option');o.value='track:'+i;o.textContent=mergedAudioLabel(nativeTrack,apiTrack,i);o.dataset.apiIndex=String(audioApiIndex(apiTrack,i));select.appendChild(o);}select.disabled=count===0;select.value=state.playerAudioChoice;if(select.selectedIndex<0){state.playerAudioChoice='auto';select.value='auto';}}
function normalizedTrackText(track){return (((track&&track.name)||'')+' '+((track&&track.label)||'')+' '+((track&&track.lang)||'')+' '+((track&&track.language)||'')).toLowerCase();}
function resolveNativeAudioTarget(listIndex){if(!video.audioTracks||!video.audioTracks.length)return -1;if(listIndex<0)return 0;var apiCount=state.playerAudios&&state.playerAudios.length||0;if(apiCount===video.audioTracks.length&&listIndex<video.audioTracks.length)return listIndex;var apiTrack=state.playerAudios[listIndex]||null,apiIndex=audioApiIndex(apiTrack,listIndex),byAbsolute=apiIndex-1;if(byAbsolute>=0&&byAbsolute<video.audioTracks.length)return byAbsolute;var lang=audioScalar(apiTrack&&typeof apiTrack==='object'&&(apiTrack.lang||apiTrack.language||apiTrack.locale)).toLowerCase(),author=firstAudioValue(apiTrack,['author','studio','team','translation']).toLowerCase();for(var i=0;i<video.audioTracks.length;i++){var text=normalizedTrackText(video.audioTracks[i]);if(lang&&(text.indexOf(lang)>=0||text.indexOf(audioLanguageName(lang).toLowerCase())>=0))return i;if(author&&text.indexOf(author)>=0)return i;}return listIndex<video.audioTracks.length?listIndex:-1;}
function setNativeAudioTrack(listIndex){if(!video.audioTracks||!video.audioTracks.length)return false;var target=resolveNativeAudioTarget(listIndex);if(target<0||!video.audioTracks[target])return false;try{for(var i=0;i<video.audioTracks.length;i++)video.audioTracks[i].enabled=i===target;return !!video.audioTracks[target].enabled;}catch(e){return false;}}
function resolveHlsAudioTarget(listIndex){var tracks=state.hls&&state.hls.audioTracks||[];if(!tracks.length)return -1;var apiTrack=state.playerAudios[listIndex]||null,apiCount=state.playerAudios&&state.playerAudios.length||0;if(apiCount===tracks.length&&listIndex<tracks.length)return listIndex;var apiIndex=audioApiIndex(apiTrack,listIndex),lang=audioScalar(apiTrack&&typeof apiTrack==='object'&&(apiTrack.lang||apiTrack.language||apiTrack.locale)).toLowerCase(),author=firstAudioValue(apiTrack,['author','studio','team','translation']).toLowerCase();for(var i=0;i<tracks.length;i++){var t=tracks[i]||{},id=Number(t.id);if(isFinite(id)&&(id===apiIndex||id===apiIndex-1))return i;var text=normalizedTrackText(t);if(lang&&(text.indexOf(lang)>=0||text.indexOf(audioLanguageName(lang).toLowerCase())>=0))return i;if(author&&text.indexOf(author)>=0)return i;}return listIndex<tracks.length?listIndex:-1;}
function applyHlsAudio(listIndex){if(!state.hls||!state.hls.audioTracks||state.hls.audioTracks.length<2)return false;var target=resolveHlsAudioTarget(listIndex);if(target<0)return false;try{state.hls.audioTrack=target;return state.hls.audioTrack===target;}catch(e){return false;}}
function destroyHls(){if(state.hls){try{state.hls.destroy();}catch(e){}state.hls=null;}state.hlsUsing=false;state.hlsManifestReady=false;}
function logicalCurrentTime(){return Math.max(0,(state.audioHlsActive?Number(state.audioHlsOffset)||0:0)+(Number(video.currentTime)||0));}
function logicalDuration(){if(state.playerOriginalDuration>0)return state.playerOriginalDuration;var d=Math.max(0,Number(video.duration)||0);return state.audioHlsActive?d+(Number(state.audioHlsOffset)||0):d;}
function currentResume(){var livePosition=logicalCurrentTime();if(livePosition>0)state.playerResumePosition=livePosition;return {position:Math.max(livePosition,Number(state.playerResumePosition)||0),paused:video.paused||video.ended};}
function prox(url,mode){return mode==='relay'?KPApi.streamProxyUrl(url):mode==='hls'?KPApi.hlsProxyUrl(url):url;}
function clearSwitchMessage(resume){var clearMessage=function(){$('playerError').textContent='';video.removeEventListener('playing',clearMessage);video.removeEventListener('canplay',clearMessage);};video.addEventListener(resume.paused?'canplay':'playing',clearMessage);}
function openUrl(url,mode,episodeId,resume,options){options=options||{};var isAudioHls=!!options.audioHls,offset=isAudioHls?Math.max(0,Number(options.offset)||0):0;if(!isAudioHls){state.audioHlsActive=false;state.audioHlsOffset=0;state.audioHlsJobId='';state.audioHlsSelectedIndex=-1;state.baseStreamUrl=url;state.baseStreamMode=mode||'direct';}else{state.audioHlsActive=true;state.audioHlsOffset=offset;state.audioHlsJobId=options.jobId||'';state.audioHlsSelectedIndex=Number(options.listIndex);}
state.streamUrl=url;state.mode=mode||'direct';state.episodeId=episodeId||'';state.streamSwitchSeq=(state.streamSwitchSeq||0)+1;var switchSeq=state.streamSwitchSeq,resumePosition=resume&&isFinite(resume.position)?Math.max(0,Number(resume.position)):Math.max(0,Number(state.playerResumePosition)||0),resumePaused=!!(resume&&resume.paused);state.playerResumePosition=Math.max(Number(state.playerResumePosition)||0,resumePosition);state.playerSwitching=true;$('playerMode').textContent=isAudioHls?'AUDIO HLS':state.mode.toUpperCase();if($('playerStreamMode')&&!isAudioHls)$('playerStreamMode').value=state.mode;video.pause();video.onloadedmetadata=null;video.oncanplay=null;destroyHls();video.removeAttribute('src');video.load();var restored=false;function restorePlayback(){if(restored||switchSeq!==state.streamSwitchSeq)return;restored=true;if(!isAudioHls&&isFinite(video.duration)&&video.duration>0)state.playerOriginalDuration=video.duration;var target=isAudioHls?Math.max(0,resumePosition-offset):resumePosition;if(isFinite(video.duration)&&video.duration>0)target=Math.min(target,Math.max(0,video.duration-.25));try{if(target>0)video.currentTime=target;}catch(e){}state.playerResumePosition=resumePosition;state.playerSwitching=false;populateAudioMenu();populateSubtitleMenu();applySubtitleChoice(state.playerSubtitleChoice);if(state.playerAudioChoice!=='auto'&&!isAudioHls&&!state.audioHlsPreparing)setTimeout(function(){applyAudioChoice(state.playerAudioChoice);},0);if(resumePaused){keepPlayerControlsVisible();return;}var p=video.play();if(p&&p.catch)p.catch(function(e){mediaError(e.message);});}
var source=options.localSource?url:prox(url,state.mode);if(state.mode==='hls'&&window.Hls&&Hls.isSupported()){state.hlsUsing=true;state.hlsManifestReady=false;state.hls=new Hls({enableWorker:true,lowLatencyMode:false,backBufferLength:600,maxBufferLength:90});state.hls.attachMedia(video);state.hls.on(Hls.Events.MEDIA_ATTACHED,function(){if(switchSeq!==state.streamSwitchSeq)return;state.hls.loadSource(source);});state.hls.on(Hls.Events.MANIFEST_PARSED,function(){if(switchSeq!==state.streamSwitchSeq)return;state.hlsManifestReady=true;populateAudioMenu();populateSubtitleMenu();restorePlayback();});state.hls.on(Hls.Events.AUDIO_TRACKS_UPDATED,function(){populateAudioMenu();});state.hls.on(Hls.Events.SUBTITLE_TRACKS_UPDATED,function(){populateSubtitleMenu();});state.hls.on(Hls.Events.ERROR,function(evt,data){if(data&&data.fatal){$('playerError').textContent='Ошибка HLS: '+(data.details||data.type||'неизвестная ошибка');}});video.onloadedmetadata=restorePlayback;video.oncanplay=restorePlayback;return;}state.hlsUsing=false;state.hlsManifestReady=false;video.src=source;video.onloadedmetadata=restorePlayback;video.oncanplay=restorePlayback;}
function audioHlsCanSeek(target){if(!state.audioHlsActive)return true;var local=Number(target)-Number(state.audioHlsOffset||0);if(local<0)return false;try{if(video.seekable&&video.seekable.length){for(var i=0;i<video.seekable.length;i++)if(local>=video.seekable.start(i)-.25&&local<=video.seekable.end(i)-.1)return true;return false;}}catch(e){}var d=Number(video.duration)||0;return d>0&&local<d-.1;}
function stopAudioHlsJob(jobId){if(!jobId)return;KPApi.stopAudioHls(jobId).catch(function(){});}
function failAudioHls(message,fallbackResume,previousChoice,token){if(token!==state.audioHlsPollToken)return;if(state.audioHlsPendingJobId){stopAudioHlsJob(state.audioHlsPendingJobId);state.audioHlsPendingJobId='';}state.audioHlsPreparing=false;state.playerAudioChoice=previousChoice||'auto';populateAudioMenu();$('playerError').textContent=message||'Не удалось подготовить выбранную звуковую дорожку.';if(fallbackResume&&!fallbackResume.paused){var p=video.play();if(p&&p.catch)p.catch(function(){});}else keepPlayerControlsVisible();}
function pollAudioHlsJob(jobId,listIndex,targetResume,fallbackResume,previousChoice,token,attempt){if(token!==state.audioHlsPollToken)return;KPApi.audioHlsStatus(jobId).then(function(info){if(token!==state.audioHlsPollToken)return;if(info.status==='failed'){failAudioHls(info.error||'Не удалось подготовить выбранную звуковую дорожку.',fallbackResume,previousChoice,token);return;}var required=Math.max(0,targetResume.position-Number(info.start_offset||0))+.75;if((info.status==='ready'||info.status==='complete')&&Number(info.available_duration||0)>=required){state.audioHlsPreparing=false;var previousJob=state.audioHlsJobId;state.audioHlsPendingJobId='';if(Number(info.original_duration)>0)state.playerOriginalDuration=Number(info.original_duration);openUrl(info.playlist_url,'hls',state.episodeId,targetResume,{audioHls:true,offset:info.start_offset,jobId:jobId,listIndex:listIndex,localSource:true});clearSwitchMessage(targetResume);if(previousJob&&previousJob!==jobId)stopAudioHlsJob(previousJob);return;}if(info.status==='complete'){failAudioHls('Подготовленный поток закончился раньше выбранной позиции.',fallbackResume,previousChoice,token);return;}if(attempt>=90){failAudioHls('Подготовка дорожки заняла больше 45 секунд. Исходный поток оставлен без изменений.',fallbackResume,previousChoice,token);return;}setTimeout(function(){pollAudioHlsJob(jobId,listIndex,targetResume,fallbackResume,previousChoice,token,attempt+1);},500);}).catch(function(err){failAudioHls('Ошибка подготовки дорожки: '+(err&&err.message?err.message:String(err)),fallbackResume,previousChoice,token);});}
function prepareAudioHls(listIndex,resumeOverride,previousChoice){var apiTrack=state.playerAudios[listIndex]||null,realIndex=audioApiIndex(apiTrack,listIndex),source=currentHttpAudioSource(),fallbackResume=currentResume(),targetResume=resumeOverride&&isFinite(resumeOverride.position)?{position:Math.max(0,Number(resumeOverride.position)||0),paused:!!resumeOverride.paused}:fallbackResume;if(!source){state.playerAudioChoice=previousChoice||'auto';populateAudioMenu();$('playerError').textContent='Для выбранного качества KinoPub не вернул исходный HTTP-файл с аудиодорожками.';return;}if(state.audioHlsPendingJobId){stopAudioHlsJob(state.audioHlsPendingJobId);state.audioHlsPendingJobId='';}state.audioHlsPollToken++;var token=state.audioHlsPollToken;state.audioHlsPreparing=true;video.pause();$('playerError').textContent='Готовим выбранную звуковую дорожку…';KPApi.createAudioHls(source,realIndex,targetResume.position).then(function(info){if(token!==state.audioHlsPollToken){if(info&&info.job_id)stopAudioHlsJob(info.job_id);return;}if(!info||!info.job_id){failAudioHls('Backend не вернул идентификатор HLS-задачи.',fallbackResume,previousChoice,token);return;}state.audioHlsPendingJobId=info.job_id;pollAudioHlsJob(info.job_id,listIndex,targetResume,fallbackResume,previousChoice,token,0);}).catch(function(err){failAudioHls('Не удалось запустить подготовку дорожки: '+(err&&err.message?err.message:String(err)),fallbackResume,previousChoice,token);});}
function applyAudioChoice(choice){var previousChoice=state.playerAudioChoice||'auto';choice=choice||'auto';if(state.audioApplyTimer){clearTimeout(state.audioApplyTimer);state.audioApplyTimer=null;}if(choice==='auto'){state.playerAudioChoice='auto';state.audioHlsPollToken++;state.audioHlsPreparing=false;if(state.audioHlsPendingJobId){stopAudioHlsJob(state.audioHlsPendingJobId);state.audioHlsPendingJobId='';}var activeJob=state.audioHlsJobId;$('playerError').textContent='';if(state.audioHlsActive){var resume=currentResume(),url=state.baseStreamUrl||streamUrlForGroup(currentQualityGroup(),state.baseStreamMode),mode=state.baseStreamMode||'direct';openUrl(url,mode,state.episodeId,resume);clearSwitchMessage(resume);stopAudioHlsJob(activeJob);}else setNativeAudioTrack(-1);return;}var index=Number(String(choice).split(':')[1]);if(!isFinite(index)||index<0)return;if(state.audioHlsActive&&state.audioHlsSelectedIndex===index&&!state.audioHlsPreparing){state.playerAudioChoice=choice;return;}state.playerAudioChoice=choice;prepareAudioHls(index,null,previousChoice);}
function play(item,episode){if(state.audioHlsJobId)stopAudioHlsJob(state.audioHlsJobId);if(state.audioHlsPendingJobId)stopAudioHlsJob(state.audioHlsPendingJobId);state.audioHlsJobId='';state.audioHlsPendingJobId='';if(!ensureSubscriptionForPlayback()){openSubscription();return;}state.audioHlsPollToken++;state.audioHlsPreparing=false;state.audioHlsActive=false;state.audioHlsOffset=0;state.audioHlsSelectedIndex=-1;state.playerAudioChoice='auto';state.playerOriginalDuration=0;state.current=item;$('playerTitle').textContent=item.title+(episode&&episode.title?' · '+episode.title:'');$('playerLayer').classList.remove('hidden');showPlayerControls();$('playerError').textContent='Получаем ссылку на видео…';var mediaId=episode&&(episode.media_id||episode.id);KPApi.play(item.id,mediaId).then(function(result){var st=result.selected||((result.streams||[])[0]);if(!st||!st.url)throw new Error('Ссылка на видео не найдена');preparePlayerOptions(result,st);$('playerError').textContent='';var preferred=state.settings.stream_mode==='auto'?(st.protocol==='hls'?'hls':'relay'):state.settings.stream_mode,group=currentQualityGroup(),initialUrl=streamUrlForGroup(group,preferred)||st.url;openUrl(initialUrl,preferred,(result.media&&result.media.id)||mediaId||'');}).catch(function(err){$('playerError').textContent='Не удалось получить поток: '+(err&&err.message?err.message:String(err));KPApi.report('Resolve stream failed',{item_id:item.id,error:String(err)},'media').catch(function(){});});}
function switchStreamMode(mode){if(!mode)return;var group=currentQualityGroup(),url=streamUrlForGroup(group,mode);if(!url){$('playerError').textContent='Для выбранного режима нет ссылки на поток.';return;}if(!state.audioHlsActive&&!state.audioHlsPreparing&&mode===state.mode)return;state.audioHlsPollToken++;state.audioHlsPreparing=false;if(state.audioHlsPendingJobId)stopAudioHlsJob(state.audioHlsPendingJobId);if(state.audioHlsJobId)stopAudioHlsJob(state.audioHlsJobId);state.audioHlsPendingJobId='';state.playerAudioChoice='auto';populateAudioMenu();var resume=currentResume();$('playerError').textContent='Переключаем поток…';openUrl(url,mode,state.episodeId,resume);clearSwitchMessage(resume);}
function switchQuality(index){var group=state.playerStreams[Number(index)];if(!group)return;state.playerQualityIndex=String(index);var mode=state.audioHlsActive?state.baseStreamMode:state.mode,url=streamUrlForGroup(group,mode);if(!url){$('playerError').textContent='Для этого качества нет подходящего потока.';return;}if(!state.audioHlsActive&&!state.audioHlsPreparing&&url===state.streamUrl)return;state.audioHlsPollToken++;state.audioHlsPreparing=false;if(state.audioHlsPendingJobId)stopAudioHlsJob(state.audioHlsPendingJobId);if(state.audioHlsJobId)stopAudioHlsJob(state.audioHlsJobId);state.audioHlsPendingJobId='';state.playerAudioChoice='auto';populateAudioMenu();var resume=currentResume();$('playerError').textContent='Меняем качество…';openUrl(url,mode,state.episodeId,resume);clearSwitchMessage(resume);}
function saveProgress(){if(!state.current)return;var savedPosition=Math.max(logicalCurrentTime(),Number(state.playerResumePosition)||0),totalDuration=logicalDuration();var completed=!!(totalDuration&&savedPosition/totalDuration>=.9);if(completed)state.watchedMap[String(state.current.id)]=1;else if(savedPosition>0&&state.watchedMap[String(state.current.id)]===undefined)state.watchedMap[String(state.current.id)]=0;KPApi.saveProgress({media_id:state.current.id,episode_id:state.episodeId||null,position:savedPosition,duration:totalDuration||0,completed:completed}).catch(function(){});}
function closePlayer(){saveProgress();state.audioHlsPollToken++;state.audioHlsPreparing=false;if(state.audioHlsPendingJobId)stopAudioHlsJob(state.audioHlsPendingJobId);if(state.audioHlsJobId)stopAudioHlsJob(state.audioHlsJobId);state.audioHlsPendingJobId='';state.audioHlsJobId='';video.pause();state.playerSwitching=false;destroyHls();video.removeAttribute('src');video.load();$('playerLayer').classList.add('hidden');$('playerLayer').classList.remove('controls-hidden');if(playerControlsTimer){clearTimeout(playerControlsTimer);playerControlsTimer=null;}}
function mediaError(m){var failedPosition=Math.max(logicalCurrentTime(),Number(state.playerResumePosition)||0);if(failedPosition>0)state.playerResumePosition=failedPosition;state.playerSwitching=false;$('playerError').textContent=m+' Позиция '+fmt(state.playerResumePosition)+' сохранена.';KPApi.report('Media error',{message:m,mode:state.mode,url:state.streamUrl,error:video.error&&video.error.code},'media').catch(function(){});}
function subscriptionDate(ts){if(!ts)return '';try{return new Date(Number(ts)*1000).toLocaleDateString('ru-RU',{day:'2-digit',month:'long',year:'numeric'});}catch(e){return '';}}
function subscriptionLabel(sub){var days=Number(sub&&sub.days);if(!sub||sub.expired||sub.active===false)return 'PRO истёк';if(!isFinite(days))return 'PRO';if(days<1)return Math.max(1,Math.ceil(days*24))+' ч.';return Math.max(1,Math.ceil(days))+' дн.';}
function applySubscription(profile){state.profile=profile||null;state.profileCheckedAt=Date.now();var chip=$('subscriptionChip');if(!chip)return;chip.classList.remove('subscription-loading','subscription-warning','subscription-critical','subscription-expired');var sub=profile&&profile.subscription||null;if(!sub){chip.textContent='—';chip.title='Не удалось определить подписку';return;}chip.textContent=subscriptionLabel(sub);var days=Number(sub.days);if(sub.expired||sub.active===false)chip.classList.add('subscription-expired');else if(isFinite(days)&&days<1)chip.classList.add('subscription-critical');else if(isFinite(days)&&days<=7)chip.classList.add('subscription-warning');chip.title=sub.expired?'Подписка закончилась':'Осталось '+chip.textContent;}
function loadProfile(refresh){var chip=$('subscriptionChip');if(chip){chip.classList.add('subscription-loading');if(!state.profile)chip.textContent='…';}return KPApi.profile(!!refresh).then(function(profile){applySubscription(profile);return profile;}).catch(function(){if(chip){chip.classList.remove('subscription-loading');if(!state.profile){chip.textContent='—';chip.title='Войдите или проверьте соединение';}}return null;});}
function openSubscription(){var profile=state.profile,sub=profile&&profile.subscription||{};var card=$('subscriptionModal').querySelector('.subscription-card');card.classList.remove('expired','warning');$('subscriptionTitle').textContent='Подписка '+appBrandName();$('subscriptionValue').textContent=subscriptionLabel(sub);var days=Number(sub.days);if(sub.expired||sub.active===false){card.classList.add('expired');$('subscriptionMessage').textContent='Подписка закончилась. Воспроизведение может быть недоступно. Продлите подписку в аккаунте KinoPub, затем нажмите «Обновить статус».';}else if(isFinite(days)&&days<=7){card.classList.add('warning');$('subscriptionMessage').textContent='Подписка скоро закончится. После продления статус обновится автоматически или по кнопке ниже.';}else{$('subscriptionMessage').textContent='Подписка активна.';}$('subscriptionEnd').textContent=sub.end_time?'Действует до '+subscriptionDate(sub.end_time):'';$('subscriptionModal').classList.remove('hidden');setTimeout(function(){$('subscriptionRefresh').focus();},20);}
function closeSubscription(){$('subscriptionModal').classList.add('hidden');}
function refreshSubscription(){var btn=$('subscriptionRefresh');btn.disabled=true;$('subscriptionValue').textContent='Проверяем…';loadProfile(true).then(function(){btn.disabled=false;openSubscription();});}
function ensureSubscriptionForPlayback(){var sub=state.profile&&state.profile.subscription;return !(sub&&(sub.expired||sub.active===false));}
function setAuthLocked(locked){state.authRequired=!!locked;document.body.classList.toggle('auth-locked',!!locked);$('authClose').classList.toggle('hidden',!!locked);}
function showAuthGate(){clearAuth();setAuthLocked(true);$('authModal').classList.remove('hidden');$('authIntro').classList.remove('hidden');$('authStart').classList.remove('hidden');$('authStart').disabled=false;$('authCodePanel').classList.add('hidden');$('authRestart').classList.add('hidden');$('verificationUri').textContent='';$('userCode').textContent='------';$('authCountdown').textContent='';$('authStatus').textContent='';setTimeout(function(){$('authStart').focus();},20);}
function loadWatchedStatuses(){return Promise.all([KPApi.watchingStatuses().catch(function(){return {statuses:{}};}),KPApi.history().catch(function(){return {items:[]};})]).then(function(results){var remote=(results[0]&&results[0].statuses)||{},local=(results[1]&&results[1].items)||[];state.watchedMap={};for(var id in remote)if(remote.hasOwnProperty(id))state.watchedMap[String(id)]=parseInt(remote[id],10);for(var i=0;i<local.length;i++){var row=local[i],mid=String(row.media_id||'');if(!mid)continue;if(row.completed)state.watchedMap[mid]=1;else if(state.watchedMap[mid]===undefined)state.watchedMap[mid]=0;}if(state.appInitialized&&state.route!=='settings')renderCatalog();return state.watchedMap;});}
function initializeAuthenticatedApp(){state.authenticated=true;setAuthLocked(false);$('authModal').classList.add('hidden');if(!state.appInitialized){state.appInitialized=true;route('popular');loadSettings();}loadProfile(true);loadWatchedStatuses();}
function startAuth(){clearAuth();$('authModal').classList.remove('hidden');$('authIntro').classList.add('hidden');$('authStart').classList.add('hidden');$('authCodePanel').classList.remove('hidden');$('authRestart').classList.add('hidden');$('verificationUri').textContent='';$('userCode').textContent='------';$('authCountdown').textContent='';$('authStatus').textContent='Получаем код…';KPApi.startAuth().then(function(d){$('verificationUri').textContent=d.verification_uri;$('userCode').textContent=d.user_code;var left=d.expires_in||300;$('authStatus').textContent='Ожидаем подтверждение';$('authCountdown').textContent='Код действует ещё '+left+' сек.';state.authTick=setInterval(function(){left--;$('authCountdown').textContent='Код действует ещё '+left+' сек.';if(left<=0){clearAuth();$('authStatus').textContent='Код истёк';$('authRestart').classList.remove('hidden');$('authRestart').focus();}},500);state.authPoll=setInterval(function(){KPApi.pollAuth(d.code).then(function(x){if(x.status==='authorized'){clearAuth();$('authStatus').textContent='Устройство подключено';setTimeout(initializeAuthenticatedApp,700);}}).catch(function(e){clearAuth();$('authStatus').textContent='Ошибка: '+e.message;$('authRestart').classList.remove('hidden');});},Math.max(5,d.interval||5)*1000);}).catch(function(e){$('authStatus').textContent='Ошибка: '+e.message;$('authRestart').classList.remove('hidden');});}
function clearAuth(){if(state.authTick)clearInterval(state.authTick);if(state.authPoll)clearInterval(state.authPoll);state.authTick=state.authPoll=null;}
function closeAuth(){if(state.authRequired)return;clearAuth();$('authModal').classList.add('hidden');}
function loadSettings(){KPApi.settings().then(function(s){state.settings=s;var icon=normalizeAppIcon(s.app_icon||'kinopub');state.settings.app_icon=icon;$('setQuality').value=s.quality;$('setMode').value=s.stream_mode;$('setAudio').value=s.audio_language;$('setSubs').value=s.subtitles;$('setAutoplay').checked=!!s.autoplay_next;$('setMotion').checked=!!s.reduce_motion;var radios=document.querySelectorAll('input[name="appIcon"]');for(var i=0;i<radios.length;i++)radios[i].checked=radios[i].value===icon;applyBranding(icon);document.body.classList.toggle('reduce-motion',!!s.reduce_motion);});}

function clearApplicationCache(){
 state.catalogCache={};
 state.catalogPages={};
 state.catalogTotals={};
 state.catalogRequest++;
 state.cacheVersion=Date.now();
 try{sessionStorage.clear();}catch(e){}
 try{localStorage.removeItem('kp_catalog_cache');}catch(e){}
 $('settingsStatus').textContent='Кэш каталога и обложек сброшен';
 KPApi.report('Frontend cache cleared',{cache_version:state.cacheVersion},'cache').catch(function(){});
 setTimeout(function(){route('popular');},350);
}
function saveSettings(){var s={quality:$('setQuality').value,stream_mode:$('setMode').value,audio_language:$('setAudio').value,subtitles:$('setSubs').value,subtitle_size:100,autoplay_next:$('setAutoplay').checked,reduce_motion:$('setMotion').checked,app_icon:selectedAppIcon()};KPApi.saveSettings(s).then(function(x){state.settings=x;x.app_icon=normalizeAppIcon(x.app_icon||'kinopub');applyBranding(x.app_icon);$('settingsStatus').textContent='Сохранено';document.body.classList.toggle('reduce-motion',!!x.reduce_motion);});}
function hideSuggestions(){var box=$('searchSuggestions');box.classList.add('hidden');box.innerHTML='';$('searchInput').setAttribute('aria-expanded','false');state.suggestionIndex=-1;}
function suggestionRows(){return $('searchSuggestions').querySelectorAll('.search-suggestion');}
function openSuggestion(item){if(!item)return;state.selectedSuggestion=item;$('searchInput').value=item.value||'';hideSuggestions();if(item.id){state.current={id:String(item.id),title:item.value||''};openDetails(state.current);return;}doSearch('title',cleanSearchQuery(item.value||''));}
function setSuggestionIndex(index){var rows=suggestionRows();if(!rows.length){state.suggestionIndex=-1;state.selectedSuggestion=null;return;}if(index<0)index=rows.length-1;if(index>=rows.length)index=0;state.suggestionIndex=index;state.selectedSuggestion=state.currentSuggestions[index]||null;for(var i=0;i<rows.length;i++)rows[i].classList.toggle('active',i===index);if(rows[index]){rows[index].scrollIntoView(false);$('searchInput').value=rows[index].getAttribute('data-value')||$('searchInput').value;}}
function renderSuggestions(items){var box=$('searchSuggestions');box.innerHTML='';state.suggestionIndex=-1;state.selectedSuggestion=null;state.currentSuggestions=items||[];if(!items||!items.length){box.innerHTML='<div class="search-suggestion-empty">Ничего не найдено…</div>';box.classList.remove('hidden');$('searchInput').setAttribute('aria-expanded','true');return;}for(var i=0;i<items.length;i++){var item=items[i],row=document.createElement('button');row.type='button';row.className='search-suggestion';row.setAttribute('role','option');row.setAttribute('data-id',item.id||'');row.setAttribute('data-value',item.value||'');row.innerHTML=highlightSuggestion(item.value||'', $('searchInput').value||'');row.onclick=(function(x){return function(){openSuggestion(x);};}(item));box.appendChild(row);}box.classList.remove('hidden');$('searchInput').setAttribute('aria-expanded','true');}
function highlightSuggestion(value,query){var safe=esc(value),q=String(query||'').trim();if(!q)return safe;var pos=String(value).toLowerCase().indexOf(q.toLowerCase());if(pos<0)return safe;return esc(String(value).slice(0,pos))+'<strong>'+esc(String(value).slice(pos,pos+q.length))+'</strong>'+esc(String(value).slice(pos+q.length));}
function cleanSearchQuery(value){return String(value||'').replace(/\s*\(\d{4}\)\s*$/,'').replace(/\s*\/.*$/,'').trim();}
function requestSuggestions(){var q=$('searchInput').value.trim();state.selectedSuggestion=null;if(state.searchTimer)clearTimeout(state.searchTimer);if(q.length<2){state.currentSuggestions=[];hideSuggestions();return;}state.searchTimer=setTimeout(function(){var seq=++state.searchSeq;KPApi.autocomplete(q).then(function(d){if(seq!==state.searchSeq||$('searchInput').value.trim()!==q)return;renderSuggestions((d&&d.items)||[]);}).catch(function(){if(seq===state.searchSeq)hideSuggestions();});},220);}
function doSearch(mode,forcedQuery){var raw=forcedQuery!==undefined?forcedQuery:$('searchInput').value.trim();var q=cleanSearchQuery(raw);if(!q)return;hideSuggestions();state.lastSearch=q;if(typeof mode==='string')state.searchMode=mode;$('catalogScreen').classList.add('hidden');$('settingsScreen').classList.add('hidden');$('searchScreen').classList.remove('hidden');$('searchPageTitle').textContent='Поиск: '+q;var modeButtons=document.querySelectorAll('[data-search-mode]');for(var m=0;m<modeButtons.length;m++)modeButtons[m].classList.toggle('active',modeButtons[m].getAttribute('data-search-mode')===state.searchMode);$('searchStatus').textContent='Ищем…';var g=$('searchResults');g.innerHTML='';KPApi.search(q,state.searchMode).then(function(d){var items=d.items||[];$('searchStatus').textContent=items.length?'Найдено: '+items.length:'';for(var i=0;i<items.length;i++)g.appendChild(card(items[i]));if(!items.length)g.innerHTML='<p class="empty-state">Ничего не найдено</p>';}).catch(function(e){$('searchStatus').textContent='Ошибка поиска';g.innerHTML='<p class="empty-state">'+esc(e&&e.message?e.message:String(e))+'</p>';});}
function diagRow(k,v){return'<div class="diag-key">'+esc(k)+'</div><div class="diag-value">'+esc(v)+'</div>';}
function openDiag(){var v=document.createElement('video'),d={userAgent:navigator.userAgent,screen:screen.width+'×'+screen.height,hls:v.canPlayType('application/vnd.apple.mpegurl')||'нет',h264aac:v.canPlayType('video/mp4; codecs="avc1.640028, mp4a.40.2"')||'нет',hevc:v.canPlayType('video/mp4; codecs="hvc1"')||'нет'};var h='';for(var k in d)h+=diagRow(k,d[k]);$('diagnosticsGrid').innerHTML=h;KPApi.health().then(function(x){$('diagnosticsGrid').innerHTML+=diagRow('backend',x.status+' '+x.version)+diagRow('API credentials',x.credentials_configured?'настроены':'не настроены');});KPApi.debugEvents().then(function(x){var l=[],a=x.events||[];for(var i=0;i<Math.min(a.length,30);i++)l.push(new Date(a[i].at*1000).toLocaleTimeString()+' ['+a[i].kind+'] '+a[i].message);$('diagnosticsLog').textContent=l.join('\n')||'Логи пусты';});$('diagnosticsModal').classList.remove('hidden');}
function openExplorer(){$('apiExplorerModal').classList.remove('hidden');setTimeout(function(){$('explorerPath').focus();},0);}function closeExplorer(){$('apiExplorerModal').classList.add('hidden');}
function runExplorer(){var p=$('explorerPath').value.trim(),q=$('explorerQuery').value.trim();if(!p)return;KPApi.explore(p,q).then(function(d){$('explorerStatus').textContent='HTTP '+(d.response?d.response.status:'?');$('explorerOutput').textContent=JSON.stringify(d,null,2);}).catch(function(e){$('explorerStatus').textContent='Ошибка';$('explorerOutput').textContent=e.message;});}
function compareFeeds(){
 $('explorerStatus').textContent='Сравниваем варианты сортировки…';$('explorerOutput').textContent='Выполняется до 9 API-запросов. Подождите…';
 KPApi.compareFeeds('both').then(function(d){
   var lines=[];
   lines.push('Снимок сайта: '+(d.snapshot||''));
   if(d.best&&d.best.popular)lines.push('Лучший для Популярных: '+d.best.popular.candidate+' — '+d.best.popular.score+'%, совпадений '+d.best.popular.overlap+'/'+d.best.popular.target_count+', точных позиций '+d.best.popular.exact_positions);
   if(d.best&&d.best.hot)lines.push('Лучший для Горячих: '+d.best.hot.candidate+' — '+d.best.hot.score+'%, совпадений '+d.best.hot.overlap+'/'+d.best.hot.target_count+', точных позиций '+d.best.hot.exact_positions);
   $('explorerStatus').textContent=lines.join(' · ');
   $('explorerOutput').textContent=JSON.stringify(d,null,2);
 }).catch(function(e){$('explorerStatus').textContent='Ошибка сравнения';$('explorerOutput').textContent=e.message;});
}
function downloadExplorer(){window.location.href=KPApi.explorerDownloadUrl($('explorerPath').value.trim(),$('explorerQuery').value.trim());}
function copyExplorer(){var t=$('explorerOutput').textContent||'',ta=document.createElement('textarea');ta.value=t;document.body.appendChild(ta);ta.select();try{document.execCommand('copy');$('explorerStatus').textContent='Ответ скопирован';}catch(e){}document.body.removeChild(ta);}
function test(mode){var u=$('testUrl').value.trim();if(!u)return;state.current={id:'diagnostic',title:'Тестовый поток',streams:[{url:u}]};$('diagnosticsModal').classList.add('hidden');$('playerLayer').classList.remove('hidden');showPlayerControls();$('playerTitle').textContent='Тестовый поток';openUrl(u,mode,'');}
function move(dir){var a=visibleFocus(),cur=document.activeElement;if(a.indexOf(cur)<0){focusFirst();return;}var r=cur.getBoundingClientRect(),best=null,score=1e9;for(var i=0;i<a.length;i++){if(a[i]===cur)continue;var b=a[i].getBoundingClientRect(),dx=b.left+b.width/2-r.left-r.width/2,dy=b.top+b.height/2-r.top-r.height/2;if(dir==='left'&&dx>=-5||dir==='right'&&dx<=5||dir==='up'&&dy>=-5||dir==='down'&&dy<=5)continue;var p=(dir==='left'||dir==='right')?Math.abs(dx):Math.abs(dy),q=(dir==='left'||dir==='right')?Math.abs(dy):Math.abs(dx),s=p+q*3;if(s<score){score=s;best=a[i];}}if(best){best.focus();try{best.scrollIntoView(false);}catch(e){}}}
document.onkeydown=function(e){var k=e.keyCode;if(k>=37&&k<=40){e.preventDefault();move(k===37?'left':k===38?'up':k===39?'right':'down');}else if(k===13&&document.activeElement&&document.activeElement.click){e.preventDefault();document.activeElement.click();}else if(k===461||k===27||k===10009){e.preventDefault();if(!$('playerLayer').classList.contains('hidden'))closePlayer();else if(!$('detailsModal').classList.contains('hidden'))closeDetails();else if(!$('apiExplorerModal').classList.contains('hidden'))closeExplorer();else if(!$('diagnosticsModal').classList.contains('hidden'))$('diagnosticsModal').classList.add('hidden');else if(!$('authModal').classList.contains('hidden'))closeAuth();else if(!$('subscriptionModal').classList.contains('hidden'))closeSubscription();else route('popular');}};
video.ontimeupdate=updatePlayerProgress;function updatePlayButton(){var b=$('togglePlay');if(!b)return;var paused=video.paused;b.setAttribute('aria-label',paused?'Воспроизвести':'Пауза');b.title=paused?'Воспроизвести':'Пауза';b.innerHTML=paused?'<svg class="icon-play" viewBox="0 0 48 48" aria-hidden="true"><path d="M17 11l22 13-22 13z"/></svg>':'<svg class="icon-pause" viewBox="0 0 48 48" aria-hidden="true"><rect x="14" y="11" width="7" height="26" rx="2"/><rect x="27" y="11" width="7" height="26" rx="2"/></svg>';};video.onplay=function(){updatePlayButton();};video.onpause=function(){updatePlayButton();saveProgress();};video.onerror=function(){var c={1:'Воспроизведение прервано',2:'Сетевая ошибка',3:'Ошибка декодирования',4:'Формат не поддерживается'};mediaError(c[video.error&&video.error.code]||'Ошибка видео');};video.onended=function(){updatePlayButton();saveProgress();if(state.route!=='settings')renderCatalog();};
var links=document.querySelectorAll('[data-route]');for(var i=0;i<links.length;i++)links[i].onclick=(function(r){return function(){route(r);};}(links[i].getAttribute('data-route')));
var iconRadios=document.querySelectorAll('input[name="appIcon"]');for(var ir=0;ir<iconRadios.length;ir++)iconRadios[ir].onchange=function(){applyBranding(this.value);};$('searchGo').onclick=function(){doSearch();};$('searchInput').oninput=requestSuggestions;$('searchInput').onfocus=requestSuggestions;$('searchInput').onkeydown=function(e){var k=e.keyCode;if(k===40&&!$('searchSuggestions').classList.contains('hidden')){e.preventDefault();e.stopPropagation();setSuggestionIndex(state.suggestionIndex+1);return;}if(k===38&&!$('searchSuggestions').classList.contains('hidden')){e.preventDefault();e.stopPropagation();setSuggestionIndex(state.suggestionIndex-1);return;}if(k===27){e.stopPropagation();hideSuggestions();return;}if(k===13){e.preventDefault();e.stopPropagation();var rows=suggestionRows();if(state.suggestionIndex>=0&&state.currentSuggestions[state.suggestionIndex]){openSuggestion(state.currentSuggestions[state.suggestionIndex]);return;}var value=$('searchInput').value.trim(),exact=null;for(var si=0;si<state.currentSuggestions.length;si++){if((state.currentSuggestions[si].value||'').trim()===value){exact=state.currentSuggestions[si];break;}}if(exact){openSuggestion(exact);}else doSearch();}};var searchModes=document.querySelectorAll('[data-search-mode]');for(var sm=0;sm<searchModes.length;sm++)searchModes[sm].onclick=(function(mode){return function(){state.searchMode=mode;doSearch(mode);};}(searchModes[sm].getAttribute('data-search-mode')));document.addEventListener('click',function(e){if(!$('searchHead').contains(e.target))hideSuggestions();});$('loginButton').onclick=function(){if(!state.authenticated)showAuthGate();};$('authStart').onclick=startAuth;$('subscriptionChip').onclick=openSubscription;$('subscriptionClose').onclick=closeSubscription;$('subscriptionRefresh').onclick=refreshSubscription;$('authClose').onclick=closeAuth;$('authRestart').onclick=startAuth;$('detailsClose').onclick=closeDetails;$('detailsPlay').onclick=function(){if(state.current)play(state.current);};$('saveSettings').onclick=saveSettings;$('clearCache').onclick=clearApplicationCache;$('diagnosticsButton').onclick=openDiag;$('diagnosticsClose').onclick=function(){$('diagnosticsModal').classList.add('hidden');};$('apiExplorerButton').onclick=openExplorer;$('apiExplorerClose').onclick=closeExplorer;$('explorerRun').onclick=runExplorer;$('compareFeeds').onclick=compareFeeds;$('explorerDownload').onclick=downloadExplorer;$('explorerCopy').onclick=copyExplorer;$('testDirect').onclick=function(){test('direct');};$('testRelay').onclick=function(){test('relay');};$('testHls').onclick=function(){test('hls');};var playbackFlashTimer=null,playerControlsTimer=null;
function showPlayerControls(){var layer=$('playerLayer');if(!layer)return;layer.classList.remove('controls-hidden');if(playerControlsTimer){clearTimeout(playerControlsTimer);playerControlsTimer=null;}if(!video.paused&&!video.ended){playerControlsTimer=setTimeout(function(){if(!video.paused&&!video.ended&&!layer.classList.contains('hidden'))layer.classList.add('controls-hidden');},3000);}}
function keepPlayerControlsVisible(){var layer=$('playerLayer');if(layer)layer.classList.remove('controls-hidden');if(playerControlsTimer){clearTimeout(playerControlsTimer);playerControlsTimer=null;}}
function showPlaybackFlash(kind){var flash=$('playbackFlash'),icon=$('playbackFlashIcon');if(!flash||!icon)return;if(playbackFlashTimer)clearTimeout(playbackFlashTimer);flash.classList.remove('show');icon.className='playback-flash-icon '+kind;void flash.offsetWidth;flash.classList.add('show');playbackFlashTimer=setTimeout(function(){flash.classList.remove('show');},500);}
function toggleVideoPlayback(showFlash){if(video.paused){var promise=video.play();if(showFlash!==false)showPlaybackFlash('play');if(promise&&promise.catch)promise.catch(function(e){mediaError(e.message);});}else{video.pause();if(showFlash!==false)showPlaybackFlash('pause');}}
function seekLogical(target){target=Math.max(0,Math.min(logicalDuration()||Infinity,target));if(state.audioHlsActive&&!audioHlsCanSeek(target)){var selected=state.audioHlsSelectedIndex>=0?state.audioHlsSelectedIndex:Number(String(state.playerAudioChoice).split(':')[1]),paused=video.paused||video.ended;if(isFinite(selected)&&selected>=0){prepareAudioHls(selected,{position:target,paused:paused},state.playerAudioChoice);return;}}var local=state.audioHlsActive?Math.max(0,target-Number(state.audioHlsOffset||0)):target;try{video.currentTime=local;}catch(e){}state.playerResumePosition=target;updatePlayerProgress();}
function seekFromTimelineEvent(e){var duration=logicalDuration();if(!isFinite(duration)||duration<=0)return;var rect=$('timeline').getBoundingClientRect();if(!rect.width)return;var x=Math.max(0,Math.min(rect.width,e.clientX-rect.left));seekLogical((x/rect.width)*duration);}
function updatePlayerProgress(){var current=logicalCurrentTime(),duration=logicalDuration();if(current>0&&!state.playerSwitching)state.playerResumePosition=current;var ratio=(duration&&isFinite(duration))?Math.max(0,Math.min(1,current/duration)):0;$('progress').style.width=(ratio*100)+'%';$('timeline').setAttribute('aria-valuenow',String(Math.round(ratio*100)));$('currentTime').textContent=fmt(current);$('duration').textContent=fmt(duration);}
$('playerLayer').onclick=function(e){if(e.target.closest&&e.target.closest('.player-controls, .timeline, .player-close-x'))return;toggleVideoPlayback();showPlayerControls();};
$('timeline').onclick=function(e){e.stopPropagation();seekFromTimelineEvent(e);};
$('timeline').onkeydown=function(e){if(e.keyCode===37||e.keyCode===39){e.preventDefault();e.stopPropagation();var step=Math.max(5,(logicalDuration()||0)*0.01);seekLogical(logicalCurrentTime()+(e.keyCode===37?-step:step));}};
$('togglePlay').onclick=function(e){e.stopPropagation();toggleVideoPlayback(false);showPlayerControls();};$('rewind').onclick=function(){seekLogical(logicalCurrentTime()-10);showPlayerControls();};$('forward').onclick=function(){seekLogical(logicalCurrentTime()+10);showPlayerControls();};$('playerStreamMode').onchange=function(e){e.stopPropagation();switchStreamMode(this.value);showPlayerControls();};$('playerQuality').onchange=function(e){e.stopPropagation();switchQuality(this.value);showPlayerControls();};$('playerSubtitles').onchange=function(e){e.stopPropagation();applySubtitleChoice(this.value);showPlayerControls();};$('playerAudio').onchange=function(e){e.stopPropagation();applyAudioChoice(this.value);showPlayerControls();};$('closePlayer').onclick=closePlayer;$('playerCloseX').onclick=function(e){e.stopPropagation();closePlayer();};$('playerLayer').onmousemove=showPlayerControls;$('playerLayer').onmouseenter=showPlayerControls;function refreshNativeTracks(){populateAudioMenu();populateSubtitleMenu();if(state.playerAudioChoice!=='auto'&&!state.audioHlsActive&&!state.audioHlsPreparing)applyAudioChoice(state.playerAudioChoice);applySubtitleChoice(state.playerSubtitleChoice);}video.addEventListener('loadedmetadata',refreshNativeTracks);video.addEventListener('loadeddata',refreshNativeTracks);video.addEventListener('canplay',refreshNativeTracks);if(video.audioTracks){video.audioTracks.onaddtrack=refreshNativeTracks;video.audioTracks.onchange=function(){populateAudioMenu();};}if(video.textTracks){video.textTracks.onaddtrack=refreshNativeTracks;video.textTracks.onchange=function(){populateSubtitleMenu();};}video.addEventListener('play',showPlayerControls);video.addEventListener('pause',keepPlayerControlsVisible);video.addEventListener('ended',keepPlayerControlsVisible);
document.body.classList.add('auth-locked');KPApi.status().then(function(s){state.authenticated=!!s.authenticated;$('loginButton').title=s.authenticated?'Профиль':'Войти';if(s.authenticated)initializeAuthenticatedApp();else{applySubscription(null);showAuthGate();}}).catch(function(){applySubscription(null);showAuthGate();});state.profileTimer=setInterval(function(){if(state.authenticated)loadProfile(false);},6*60*60*1000);document.addEventListener('visibilitychange',function(){if(!document.hidden&&state.authenticated&&Date.now()-state.profileCheckedAt>30*60*1000)loadProfile(false);});
}());
